"""Fallback Policy — Knowledge Response.

NOT a Tool Executor. This is a behavior triggered when ALL executors fail.
Produces a Document labelled UNVERIFIED. The Router invokes this only after
every capable executor has been tried.
"""
from fetcher.base import Document


class FallbackPolicy:
    """Activated when all executors fail. Returns an UNVERIFIED Document."""

    async def respond(
        self, query: str = "", url: str = None, errors: list = None
    ) -> Document:
        return Document(
            source="knowledge_fallback",
            url=url or "",
            domain="",
            executor="knowledge_fallback",
            verification_status="UNVERIFIED",
            confidence=0.0,
            content=None,
            markdown=None,
            errors=errors or ["all executors failed"],
            warnings=[
                "Response generated by fallback policy, NOT fetched from source. "
                "Marked UNVERIFIED — do not treat as ground truth."
            ],
        )
